<h1>Mis notas: NumPy<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Intro" data-toc-modified-id="Intro-0"><span class="toc-item-num">0&nbsp;&nbsp;</span>Intro</a></span></li><li><span><a href="#Arrays" data-toc-modified-id="Arrays-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Arrays</a></span><ul class="toc-item"><li><span><a href="#Creación" data-toc-modified-id="Creación-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Creación</a></span></li><li><span><a href="#Atributos" data-toc-modified-id="Atributos-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Atributos</a></span></li><li><span><a href="#Indexado" data-toc-modified-id="Indexado-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Indexado</a></span></li><li><span><a href="#Slicing" data-toc-modified-id="Slicing-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Slicing</a></span></li><li><span><a href="#Sub-arrays" data-toc-modified-id="Sub-arrays-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Sub-arrays</a></span></li><li><span><a href="#Copias-de-arrays" data-toc-modified-id="Copias-de-arrays-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Copias de arrays</a></span></li><li><span><a href="#Reformateo-de-arrays" data-toc-modified-id="Reformateo-de-arrays-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Reformateo de arrays</a></span></li><li><span><a href="#Concatenación-y-división" data-toc-modified-id="Concatenación-y-división-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Concatenación y división</a></span></li></ul></li><li><span><a href="#Funciones-universales-de-NumPy" data-toc-modified-id="Funciones-universales-de-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Funciones universales de NumPy</a></span><ul class="toc-item"><li><span><a href="#Funciones-aritméticas" data-toc-modified-id="Funciones-aritméticas-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Funciones aritméticas</a></span></li><li><span><a href="#Valor-absoluto" data-toc-modified-id="Valor-absoluto-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Valor absoluto</a></span></li><li><span><a href="#Funciones-trigonométricas" data-toc-modified-id="Funciones-trigonométricas-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Funciones trigonométricas</a></span></li><li><span><a href="#Funciones-exponenciales-y-logarítmicas" data-toc-modified-id="Funciones-exponenciales-y-logarítmicas-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Funciones exponenciales y logarítmicas</a></span></li><li><span><a href="#Funciones-especializadas" data-toc-modified-id="Funciones-especializadas-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Funciones especializadas</a></span></li><li><span><a href="#Agregados" data-toc-modified-id="Agregados-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Agregados</a></span></li><li><span><a href="#Producto-tensorial" data-toc-modified-id="Producto-tensorial-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span>Producto tensorial</a></span></li></ul></li><li><span><a href="#Agregaciones" data-toc-modified-id="Agregaciones-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Agregaciones</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Broadcasting</a></span></li></ul></div>

## Intro

[NumPy](http://www.numpy.org/) (Numerical Python) es una librería para tratar grandes cantidades de datos. Los arrays de NumPy proporcionan almacenamiento y operaciones mucho más eficientes que los arrays estándar de Python cuando los datos empiezan a crecer. Esto convierte a NumPy en parte indispensable dentro del ecosistema de Data Science con Python.


In [1]:
# NumPy suele importarse con el alias np
import numpy as np

# np?

Igual que un tipo primitivo es más que un simple valor en Python por el tipado dinámico (en realidad se trata de una estructura de C), una lista es más que una simple lista de objetos (pueden albergar todo tipo de objetos simultáneamente). 

Esta flexibilidad tiene un precio, ya que cada objeto en una lista debe incluir información del tipo (entre otras cosas). En el caso de que todos los elementos fueran de un mismo tipo podríamos eliminar la redundancia para ganar en eficiencia de almacenado; esto es precisamente lo que aportan el objeto **array** disponible en Python desde la versión 3.3.

El objeto **ndarray** de NumPy, aparte de las ventajas del array, aporta también operaciones eficientes sobre sus datos.

## Arrays

### Creación

Podemos crear arrays a partir de listas, usando el método:

**np.array(`<list>`[, dtype='`<type>`'])**

Para ver la lista de tipos básicos de NumPy: [Doc:  Data types](https://docs.scipy.org/doc/numpy/user/basics.types.html)

In [2]:
# Ejemplo con integer
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
# Ejemplo con tipos integer y float => upcasting a float!
np.array([1, 2.5, 3])

array([1. , 2.5, 3. ])

También podemos crear arrays sin usar una lista:

In [4]:
# Crear un array vacío (muestra lo que sea que haya en memoria). Útil para inicializarlo.
np.empty(4) 

array([8.18657733e-312, 2.07598675e+243, 1.90886933e+136, 8.91387244e+160])

In [5]:
# Crear un array usando un intervalo, indicando el salto
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
# Crear un array usando un intervalo, indicando el número de elementos
np.linspace(0, 9, 7) 

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [7]:
# Crear un array de ceros (float por defecto)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
# Especificando el tipo.
np.zeros(5, dtype='int')

array([0, 0, 0, 0, 0])

In [9]:
# Crear una matriz (array bidimensional) de unos. Ojo cómo definimos el tipo (opción b)
np.ones((3, 3), dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
# Crear una matriz con un valor concreto. Esta vez probamos con un array de 3 dimensiones!
np.full((2, 2, 2), 3.14)

array([[[3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14]]])

In [11]:
# Crear una matriz de números aleatorios entre 0 y 1
np.random.seed(0) # semilla para reproducibilidad
np.random.random((3, 3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [12]:
# Crear una matriz de números enteros aleatorios dentro de un intervalo
np.random.randint(0, 10, (3, 3))

array([[1, 6, 7],
       [7, 8, 1],
       [5, 9, 8]])

In [13]:
# Crear una matriz identidad
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Atributos

In [14]:
# Array tridimensional de ejemplo
m = np.random.random((2, 2, 2))
m

array([[[0.0871293 , 0.0202184 ],
        [0.83261985, 0.77815675]],

       [[0.87001215, 0.97861834],
        [0.79915856, 0.46147936]]])

In [15]:
# Atributos comunes
print('m.ndim =', m.ndim)          # dimensiones
print('m.shape =', m.shape)        # tamaño
print('m.size =', m.size)          # nº de elementos
print('m.dtype =', m.dtype)        # tipo
print('m.itemsize =', m.itemsize)  # tamaño de cada elemento, en bytes
print('m.nbytes =', m.nbytes)      # tamaño total

m.ndim = 3
m.shape = (2, 2, 2)
m.size = 8
m.dtype = float64
m.itemsize = 8
m.nbytes = 64


### Indexado

In [16]:
# Array de ejemplo
a = np.arange(0,10)

In [17]:
# Acceso a un elemento de un array
a[0]

0

In [18]:
# Acceso a un elemento por el final
a[-1]

9

In [19]:
# Acceso a un elemento de una matriz
m[0, 0, 0] # equivalente a m[0][0][0]

0.08712929970154071

### Slicing

In [20]:
# [start:stop:step]
a[0:6:2]

array([0, 2, 4])

In [21]:
# [start:stop:step] desde el final
a[3:0:-1] # 9 8 7 6 5 4 [3 2 1] 0

array([3, 2, 1])

In [22]:
# Uno de cada 2 empezando por el segundo elemento
a[1::2]

array([1, 3, 5, 7, 9])

In [23]:
# Arrays multidimensionales
m[:1, :2, :1] 

array([[[0.0871293 ],
        [0.83261985]]])

In [24]:
aa = np.array([a, a])
aa

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
# Elementos de la primera columna
print(aa[:,0])

[0 0]


In [26]:
# Elementos de la primera fila
print(aa[0,:]) # Equivalente a aa[0]

[0 1 2 3 4 5 6 7 8 9]


### Sub-arrays
Si creamos un sub-array y modificamos algo del mismo, se modificará el array original. Este comportamiento por defecto nos permite cargar una parte de un dataset para operar sobre los datos, evitando cargar el array completo cuando éste es demasiado grande.

In [27]:
aaa = aa[:2,:2]
aaa

array([[0, 1],
       [0, 1]])

In [28]:
aaa[:,0] = [5, 5]
aaa

array([[5, 1],
       [5, 1]])

In [29]:
aa

array([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Copias de arrays
Si queremos crear una copia de un array o parte del mismo, tendremos que usar la función **copy()**

In [30]:
aaa_copy = aa[:2,:2].copy()
aaa_copy

array([[5, 1],
       [5, 1]])

### Reformateo de arrays
Útil para cambiar la forma de un array. Eso sí, el número de elementos tendrá que encajar. Tenemos las funciones **reshape** y **newaxis**

In [31]:
# Paso de un array unidimensional (9) a uno bidimensional (3,3)
np.arange(1, 10).reshape((3, 3)) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# Paso de un array unidimensional (9) a uno bidimensional (1,9)
np.arange(1, 10).reshape((1, 9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
# Lo mismo usando newaxis
a[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### Concatenación y división

In [34]:
# Concatenación de arrays unidimensionales
np.concatenate([a, a, a])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Concatenación de arrays bidimensionales con mismo tamaño, por filas
np.concatenate([aaa_copy, aaa_copy])

array([[5, 1],
       [5, 1],
       [5, 1],
       [5, 1]])

In [36]:
# Lo mismo pero por columnas
np.concatenate([aaa_copy, aaa_copy], axis=1)

array([[5, 1, 5, 1],
       [5, 1, 5, 1]])

In [37]:
# Concatenación para arrays con distintas dimensiones, en vertical
np.vstack([aaa_copy, aaa_copy[0]])

array([[5, 1],
       [5, 1],
       [5, 1]])

In [38]:
# Concatenación para arrays con distintas dimensiones, en horizontal
np.hstack([aa, aaa_copy])

array([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 1],
       [5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 1]])

Usaremos **dstack** para concatenar en la tercera dimensión.

Lo contrario a la concatenación es la división, que llevaremos a cabo con **split**, **hsplit**, **vsplit** y **dsplit**

In [39]:
a1, a2, a3, a4 = np.split(a, [1, 3, 6])
print(a1, a2, a3, a4)

[0] [1 2] [3 4 5] [6 7 8 9]


## Funciones universales de NumPy

La clave para que las operaciones sobre arrays de NumPy sean eficientes es usar operaciones **vectorizadas**: ejecutadas sobre un vector, aplicadas sobre cada elemento. Este tipo de operaciones están implementadas en NumPy a través de sus funciones universales (**ufuncs**).

Distinguimos 2 tipos de ufuncs: unarias (una entrada) y binarias (dos).

Cada vez que veamos un bucle que actúa sobre los elementos de un objeto deberemos considerar la opción de sustituirlo por una operación vectorizada.

In [40]:
# Ejemplo con un array y un escalar
b = a/10
b

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [41]:
# Ejemplo con 2 arrays
a + b

array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

Podemos mejorar el rendimiento de una operación especificando el array de salida de la misma, en lugar de hacer una asignación; de esa manera nos ahorraremos la creación de un array temporal y la copia de sus elementos al array final

In [42]:
# Ejemplo
y = np.zeros(10)
np.power(2, a[0:5], out=y[::2]) # más eficiente que y[::2] = np.power(2, a[0:5])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


### Funciones aritméticas
Todas las operaciones aritméticas nativas de Python están soportadas por NumPy, y se pueden escribir de dos formas:

 * `+` = np.add()
 * `-` = np.subtract()
 * `-` = np.negative()
 * `*` = np.multiply()
 * `/` = np.divide()
 * `//` = np.floor_divide()
 * `**` = np.power()
 * `%` = np.mod()

### Valor absoluto

 * `np.absolute(x)` | `np.abs(x)`

In [43]:
# Ejemplo array de enteros
c = np.arange(-2, 3)
np.absolute(c)

array([2, 1, 0, 1, 2])

In [44]:
# Ejemplo array complejo
c = np.array([1 - 1j, -1 - 2j, 1 + 0j, 0 + 1j])
np.abs(c)

array([1.41421356, 2.23606798, 1.        , 1.        ])

### Funciones trigonométricas

 * `np.sin(x)` : seno
 * `np.cos(x)` : coseno
 * `np.tan(x)` : tangente
 
 
 * `np.arcsin(x)` : arco seno
 * `np.arccos(x)` : arco coseno
 * `np.arctan(x)` : arco tangente

### Funciones exponenciales y logarítmicas

 * `np.exp(x)` : e\*\*x
 * `np.expm1(x)` : e\*\*x - 1 # para x ~ 0
 * `np.exp2(x)` : 2\*\*x 
 * `np.power(base, x)` : base\*\*x
 
 
 * `np.log(x)` : ln(x)
 * `np.log1p(x)` : ln(1 + x) # para x ~ 0
 * `np.log10(x)` : log10(x)
 * `np.log2(x)` : log2(x)

### Funciones especializadas
NumPy tiene muchas más funciones para todo tipo de operaciones matemáticas (ver documentación). Y si queremos alguna función más específica, es muy posible que la podamos encontrar ya disponible en el módulo **scipy.special**.

In [45]:
from scipy import special

#Ejemplos
print('special.gamma(b) =', special.gamma(b))
print('special.erf(b) =', special.erf(b))

special.gamma(b) = [       inf 9.5135077  4.59084371 2.99156899 2.21815954 1.77245385
 1.48919225 1.29805533 1.16422971 1.0686287 ]
special.erf(b) = [0.         0.11246292 0.22270259 0.32862676 0.42839236 0.52049988
 0.60385609 0.67780119 0.74210096 0.79690821]


### Agregados
Aparte de poder realizar operaciones de un array con un escalar, o de un array con otro array, podemos usar operaciones entre los propios elementos de un array. Podremos aplicar cualquier ufunc binaria (con dos entradas) usando el método **reduce** y aplicaremos la operación: a los 2 primeros elementos, a su resultado con el tercero, a este resultado con el cuarto, etc.

In [46]:
# Ejemplo con la operación resta
np.subtract.reduce(a)

-45

Si en vez de obtener un resultado final lo que buscamos es obtener un array con todos los resultados parciales, usaremos **accumulate**

In [47]:
np.subtract.accumulate(a)

array([  0,  -1,  -3,  -6, -10, -15, -21, -28, -36, -45], dtype=int32)

### Producto tensorial
Obtendremos una matriz con los resultados de aplicar una operación a todas las combinaciones entre los elementos de un vector y los elementos de otro.

In [48]:
np.multiply.outer(a, a)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

## Agregaciones
NumPy cuenta con funciones agregadoras optimizadas para el estudio estadístico de los datasets.

 * Suma: `x.sum()` = np.sum(x)
 * Máximo: `x.max()` = np.max(x)
 * Mínimo: `x.min()` = np.min(x)
 * Producto: `x.prod()` = np.prod(x)
 * Media: `x.mean()` = np.mean(x)
 * Desviación: `x.std()` = np.std(x)
 * Varianza: `x.var()` = np.var(x)
 * Índice máximo: `x.argmax()` = np.argmax(x)
 * Índice mínimo: `x.argmin()` = np.argmin(x)
 * Mediana: `x.median()` = np.median(x)
 * Percentil: `x.percentile(percentage)` = np.percentile(x, percentage) _# x.percentile(50) = x.median()_
 * OR: `x.any()` = np.any(x)
 * AND: `x.all()` = np.all(x)
 
 Existe una versión segura de cada función (menos de las dos últimas), usando el prefijo `nan`. Dichas funciones ignorarán los valores "faltantes", representados por el valor **NaN**.
 
 Estas funciones son aplicables a arrays de cualquier dimensión, con parámetros añadidos:

In [49]:
# Array de ejemplo
aaa

array([[5, 1],
       [5, 1]])

In [50]:
# Suma aplicada a columnas
aaa.sum(axis=0) # axis especifica la dimensión que será eliminada; en este caso las filas

array([10,  2])

In [51]:
# Suma aplicada a filas
aaa.sum(axis=1)

array([6, 6])

## Broadcasting