**Disclaimer**: Este notebook contiene mis notas sobre Pandas, resumiendo básicamente el [capítulo 3](https://jakevdp.github.io/PythonDataScienceHandbook/03.00-introduction-to-pandas.html) de [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) escrito por [Jake VanderPlas](http://vanderplas.com/). Recomiendo leer la fuente original e ir ejecutando todos los ejemplos (___learn by doing!___).

## Intro

[Pandas](https://pandas.pydata.org/) (Numerical Python) es una librería construída sobre NumPy para manipular estructuras de datos heterogéneos y etiquetados (dataframes). Pandas ofrece herramientas para tratar estas estructuras de forma eficiente, pudiendo realizar análisis de datos extensivos.

Los arrays de NumPy son perfectos para trabajar con datos limpios y organizados usando operaciones numéricas, pero sus limitaciones son claras cuando necesitamos flexibilidad (etiquetar datos, trabajar con datos faltantes, operaciones que no encajen con broadcasting, datos heterogéneos, etc). Pandas introduce los objetos **Series** y **DataFrame** para poder llevar a cabo las tareas de acomodar y pulir los datos en crudo con el fin de preparar los datos para su análisis.

Para poder usar Pandas, simplemente tendremos que importar la librería :)

In [1]:
# Pandas suele importarse con el alias pd
import pandas as pd

In [2]:
# Resto de imports
import numpy as np

## Objetos de Pandas

### El objeto `Series`

Se trata de un array unidimensional de datos indexados. Los índices son explícitos, lo que diferencia un objeto Series de Pandas de un array de NumPy, y además nos permite usar índices de cualquier otro tipo que no sea entero.

Podemos ver el objeto Series también como un caso particular de un diccionario de Python, pero ordenado (permitiendo slicing) y con mejor eficiencia para casos determinados, debido a que todos los índices son del mismo tipo.

Podemos crearlo a partir de una lista, un array de NumPy o un diccionario (en este último caso los índices por defecto serán las claves del diccionario ordenadas). Podemos incluso crearlo a partir de un escalar, que se repetirá tantas veces como longitud tenga el índice.

In [3]:
# Ejemplo a partir de un array sin especificar los índices (por defecto será una secuencia de enteros)
pd.Series([0, 0.25, 0.5, 0.75, 1.0])

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [4]:
# Mismo ejemplo especificando los índices
serie = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
                index=[0, 'a', 'b', 'c', 'e'])
serie

0    0.00
a    0.25
b    0.50
c    0.75
e    1.00
dtype: float64

In [5]:
# Ejemplo a partir de un diccionario, usando index para quedarnos sólo una parte
pd.Series({1:'a', 2:'b', 3:'c'}, index=[3, 2])

3    c
2    b
dtype: object

Para obtener los valores del objeto Series usamos el atributo **values**. Devuelve un array de NumPy.

In [6]:
serie.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Para obtener los índices usamos el atributo **index**. Devuelve una especie de array de tipo pd.Index.

In [7]:
serie.index

Index([0, 'a', 'b', 'c', 'e'], dtype='object')

### El objeto `DataFrame`

Se trata de un array bidimensional de datos doblemente indexados; esto es, una matriz de filas y columnas etiquetadas. Podemos verlo también como una versión ordenada de un diccionario de objetos Series.

Creamos un ejemplo de DataFrame usando 2 diccionarios de partida:

In [8]:
provinces_population = {'Madrid': 6578079, 'Barcelona': 5609350, 'Valencia': 2547986, 
                        'Sevilla': 1939887, 'Alicante': 1838819}
provinces_community = {'Madrid': 'Comunidad de Madrid', 'Valencia': 'Comunidad Valenciana', 
                        'Sevilla': 'Andalucía', 'Alicante': 'Comunidad Valenciana', 'Bilbao': 'Euskadi'}

# Creamos un diccionario con 2 claves, una para cada diccionario:
provinces = pd.DataFrame({'population': provinces_population, 'community': provinces_community})
provinces

population             community
Alicante    1838819.0  Comunidad Valenciana
Barcelona   5609350.0                   NaN
Bilbao            NaN               Euskadi
Madrid      6578079.0   Comunidad de Madrid
Sevilla     1939887.0             Andalucía
Valencia    2547986.0  Comunidad Valenciana

Como podemos observar, cuando no coinciden los índices de los diccionarios se rellenarán los huecos con NaN ("Not a Number").

En el atributo **index** tendremos los índices de las filas:

In [9]:
provinces.index

Index(['Alicante', 'Barcelona', 'Bilbao', 'Madrid', 'Sevilla', 'Valencia'], dtype='object')

En el atributo **columns** tendremos los índices de las columnas:

In [10]:
provinces.columns

Index(['population', 'community'], dtype='object')

En el atributo **values** estarán todos los valores:

In [11]:
provinces.values

array([[1838819.0, 'Comunidad Valenciana'],
       [5609350.0, nan],
       [nan, 'Euskadi'],
       [6578079.0, 'Comunidad de Madrid'],
       [1939887.0, 'Andalucía'],
       [2547986.0, 'Comunidad Valenciana']], dtype=object)

Podemos crear un DataFrame de muchas maneras. En el ejemplo hemos visto cómo crearlo a partir de un diccionario de diccionarios (que también podría haber sido un diccionario de objetos Series). A continuación más ejemplos:

In [12]:
# DataFrame creado a partir de un único objeto Series:
pd.DataFrame(serie, columns=['valor'])

valor
0   0.00
a   0.25
b   0.50
c   0.75
e   1.00

In [13]:
# DataFrame creado a partir de una lista de diccionarios (cada elemento será una fila)
pd.DataFrame([{'a': i, 'b': i**2} for i in range(1, 4)])

a  b
0  1  1
1  2  4
2  3  9

In [14]:
# DataFrame creado a partir de un array bidimensional de NumPy
pd.DataFrame(np.random.rand(2,3), columns=['a', 'b', 'c'], index=[1, 2])

a         b         c
1  0.731021  0.672467  0.334861
2  0.903432  0.407639  0.034392

También podemos crear un DataFrame directamente a partir de un array estructurado de NumPy:

In [15]:
pd.DataFrame(np.ones(3, dtype=[('A', 'i8'), ('B', 'f8')]))

A    B
0  1  1.0
1  1  1.0
2  1  1.0

Finalmente, podemos transponer el DataFrame como si fuera una matriz

In [16]:
provinces.T

Alicante    Barcelona   Bilbao               Madrid  \
population           1.83882e+06  5.60935e+06      NaN          6.57808e+06   
community   Comunidad Valenciana          NaN  Euskadi  Comunidad de Madrid   

                Sevilla              Valencia  
population  1.93989e+06           2.54799e+06  
community     Andalucía  Comunidad Valenciana

### El objeto `Index`

Ya hemos podido usar esta estructura en los ejemplos de Series y DataFrame. Podemos verlo como un array **inmutable**. Que los índices no sean modificables es una medida de seguridad por si varios objetos comparten el mismo Index.

Podemos construir un objeto Index:

In [17]:
# Ejemplo
ind = pd.Index([3, 6, 9, 12, 15])
ind

Int64Index([3, 6, 9, 12, 15], dtype='int64')

Como en los arrays, podemos acceder a un elemento o hacer slicing con corchetes. Además tendremos acceso a atributos disponibles en NumPy:

In [18]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


El objeto Index puede verse también como un conjunto ordenado. ¿Por qué? porque podemos calcular la intersección (`&`), la unión (`|`), o la diferencia simétrica (`^`) de dos objetos Index.

## Indexado y selección de datos

### Series

In [19]:
# Ejemplo
serie

0    0.00
a    0.25
b    0.50
c    0.75
e    1.00
dtype: float64

Como en Numpy podemos **indexar** sus elementos usando corchetes:

In [20]:
# Obtener el valor en un índice
serie['e']

1.0

El **slicing** tiene una particularidad; si lo hacemos con índices explícitos, el último índice está incluido en la selección. En cambio, si usamos índices implícitos, el último índice está excluido como siempre. 

In [21]:
# Slicing por índices explícitos
serie['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [22]:
# Slicing por índices implícitos
serie[0:2]

0    0.00
a    0.25
dtype: float64

In [23]:
# Masking
serie[(serie > 0.4) & (serie < 0.6)]

b    0.5
dtype: float64

In [24]:
# Indexado múltiple (fancy)
serie[[0, 'e']]

0    0.0
e    1.0
dtype: float64

Si tenemos índices numéricos explícitos, las operaciones de indexado usarán estos índices, pero las operaciones de slicing usarán los índices implícitos.

In [25]:
serie2 = pd.Series(['a', 'b', 'c'], index=[2, 3, 4])

serie2[2]

'a'

In [26]:
serie2[1:3]

3    b
4    c
dtype: object

Para evitar este tipo de confusiones, Pandas proporciona unos atributos especiales para el objeto Series:
 * `loc` : referencia a los índices explícitos
 * `iloc` : referencia a los índices implícitos
 * `ix` : *deprecated*
 
Es recomendable escribirlos siempre, y usar índices explícitos en lugar de implícitos siempre que podamos.

In [27]:
# Ejemplo
serie2.iloc[2]

'c'

In [28]:
# Ejemplo
serie2.loc[1:3]

2    a
3    b
dtype: object

### DataFrame

In [29]:
# Ejemplo
provinces

population             community
Alicante    1838819.0  Comunidad Valenciana
Barcelona   5609350.0                   NaN
Bilbao            NaN               Euskadi
Madrid      6578079.0   Comunidad de Madrid
Sevilla     1939887.0             Andalucía
Valencia    2547986.0  Comunidad Valenciana

Para **indexar** los datos podemos especificar un único índice (por defecto es un índice explícito), con lo que obtendremos una columna indexada. La columna no es más que un objeto de tipo Series. También podemos especificar un segundo índice, con lo que obtendríamos un único valor:

In [30]:
# Indexado. Usando corchetes o el típico acceso a un atributo (provinces.population).
# NOTA: Mejor corchetes! lo otro no funciona si la columna se llama igual que un método de DataFrame, como por ejemplo pop.
provinces['population']

Alicante     1838819.0
Barcelona    5609350.0
Bilbao             NaN
Madrid       6578079.0
Sevilla      1939887.0
Valencia     2547986.0
Name: population, dtype: float64

In [31]:
# Indicamos un índice / fila dentro de esa misma serie 
provinces['population']['Madrid']

6578079.0

In [32]:
# Podemos usar el indexado para crear una nueva columna:
provinces['population_M'] = round(provinces['population'] / 1000000, 2)
provinces

population             community  population_M
Alicante    1838819.0  Comunidad Valenciana          1.84
Barcelona   5609350.0                   NaN          5.61
Bilbao            NaN               Euskadi           NaN
Madrid      6578079.0   Comunidad de Madrid          6.58
Sevilla     1939887.0             Andalucía          1.94
Valencia    2547986.0  Comunidad Valenciana          2.55

In [33]:
# Podemos seleccionar una fila concreta en lugar de una columna usando los índices implícitos
provinces.iloc[3]

population              6.57808e+06
community       Comunidad de Madrid
population_M                   6.58
Name: Madrid, dtype: object

In [34]:
# También podemos seleccionar sólo los valores de una fila con el atributo values
provinces.values[3]

array([6578079.0, 'Comunidad de Madrid', 6.58], dtype=object)

In [35]:
# Seleccionar un valor con índices explícitos como si de un array se tratase
provinces.loc['Madrid', 'population_M'] # Equivalente a provinces['population_M']['Madrid']

6.58

In [36]:
# Seleccionar un valor con índices implícitos
provinces.iloc[3, 2]

6.58

El **slicing**, al contrario que el indexado, se hace sobre filas

In [37]:
# Slicing con índices explícitos
provinces['Barcelona':'Madrid']

population            community  population_M
Barcelona   5609350.0                  NaN          5.61
Bilbao            NaN              Euskadi           NaN
Madrid      6578079.0  Comunidad de Madrid          6.58

In [38]:
# Slicing con índices implícitos
provinces.iloc[:2, 1:]

community  population_M
Alicante   Comunidad Valenciana          1.84
Barcelona                   NaN          5.61

In [39]:
# Slicing con índices explícitos
provinces.loc[:'Barcelona', 'community':]

community  population_M
Alicante   Comunidad Valenciana          1.84
Barcelona                   NaN          5.61

In [40]:
# Podemos combinar masking con indexado múltiple
provinces.loc[provinces.population_M > 4, ['community', 'population']]

community  population
Barcelona                  NaN   5609350.0
Madrid     Comunidad de Madrid   6578079.0